---

- name: Backup Web
  hosts: "{{ hosts }}"
  gather_facts: no

  tasks:
    - name: tgz domain folder
      command: "tar -czf ../{{ run_timestamp }}-{{ env }}-sanfilippoinitiative.tgz ."
      args:
        chdir: "{{ sanfilippoinitiative.root_dir }}"

    - name: download file
      fetch:
        dest: "{{ pwd }}/ansible/files/backup/"
        flat: yes
        src: "{{ sanfilippoinitiative.root_dir }}/../{{ run_timestamp }}-{{ env }}-sanfilippoinitiative.tgz"

- name: Backup DB
  hosts: "{{ hosts }}"
  gather_facts: no

  tasks:
    - name: noop
      command: echo noop
